apiVersion: ibm.com/v1
kind: IBMSecurityVerifyAccess
metadata:
  name: ibmsecurityverifyaccess-sample
spec:
  image: "ibmcom/verify-access-wrp:10.0.3.0"

  size: 1
  autoRestart: true
  snapshotId: published
