# permissions for end users to edit ibmsecurityverifyaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmsecurityverifyaccess-editor-role
rules:
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifyaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifyaccesses/status
  verbs:
  - get
