##############################################################################
# Copyright contributors to the IBM Security Verify Access Operator project

# This workflow will be triggered whenever a push occurs on specific
# branches (e.g. when a pull request is merged).  The action will build and
# publish the verify access operator.  The docker images will be
# published to docker hub for 'master' builds, and a private
# artifactory repository for 'development' builds.

name: verify-access-operator-publish

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - development
      - build-environment

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The jobs for the workflow.
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the 
    # job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can 
      # access it
      - name: Checkout
        uses: actions/checkout@v2

      # Set up the GO environment.
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      # Set up the GO cache.
      - name: Use go cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up OperatorSDK
        id: fetch-operator-sdk
        run: |
          env
          echo $PWD
          ls $PWD
          ls /

      # Perform the build.
      - name: Update type definitions
        run: make generate
      - name: Update CRD
        run: make manifests
      - name: Build code
        run: make build
      - name: Build bundle
        run: make bundle

